### ISSUE TITLE
deployment stops and throws exception

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/mail-dispatcher#23]
mail dispatcher throws exception if record exists.
@danielrampanelli Is this a wanted behaviour?
```
info: Deploying configuration and mappings...
info: Configured domains: [ 'cocos.bz.it' ]
info: Processing domain: cocos.bz.it
info: Applying changes to DNS records
info: Cleaned up 1 records
(node:17198) UnhandledPromiseRejectionWarning: InvalidChangeBatch: [Tried to create resource record set [name='krs._domainkey.cocos.bz.it.', type='TXT'] but it already exists]
    at Request.extractError (/home/patrick/git/mail-dispatcher/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/home/patrick/git/mail-dispatcher/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/patrick/git/mail-dispatcher/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/patrick/git/mail-dispatcher/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/patrick/git/mail-dispatcher/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/patrick/git/mail-dispatcher/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/patrick/git/mail-dispatcher/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/patrick/git/mail-dispatcher/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/patrick/git/mail-dispatcher/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/patrick/git/mail-dispatcher/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:17198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by danielrampanelli** [comment]
It's not a wanted behaviour, thanks for the feedback.
